# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0049_userprofile_pm_content_in_desktop_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmalias',
            name='subdomains_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='realmalias',
            unique_together=set([('realm', 'domain')]),
        ),
    ]
