# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import zerver.models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0182_set_initial_value_is_private_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='plan_type',
            field=models.PositiveSmallIntegerField(default=zerver.models.default_plan_type),
        ),
    ]
